### ISSUE TITLE
Qt/QML

### ISSUE THREAD

**Issue by Ace-Krypton** [afendin/KalmanFilterWorkbench#1]
Salam, Qt/QML oyrenmek sene ne qeder vaxta basa geldi? 
Projectimde istifade elemey isteyirem ama basqa alternetivlerimde var ImGUI kimi, ama bilmirem deqiq hansi daha yaxsi olar.

**Comment by afendin** [comment]
@Ace-Krypton Salam, tam yadimda deyil, coxdan idi, amma bele deyek maximum 180 saat. Baxir projecte eslinde. ImGUI ile tecrubem olmayib.
